//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sega.Sonic3k.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sega.Sonic3k.Launcher.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable DDRAW Wrapper.
        /// </summary>
        internal static string DisableDdrawWrapper {
            get {
                return ResourceManager.GetString("DisableDdrawWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : NOT RECOMMENDED.
        /// </summary>
        internal static string DisableDdrawWrapperWarning {
            get {
                return ResourceManager.GetString("DisableDdrawWrapperWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM Synthetizer.
        /// </summary>
        internal static string FMSynth {
            get {
                return ResourceManager.GetString("FMSynth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - F4 : Display mode change - Alt-F4 : Exit game -.
        /// </summary>
        internal static string GameAid {
            get {
                return ResourceManager.GetString("GameAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General MIDI.
        /// </summary>
        internal static string GeneralMIDI {
            get {
                return ResourceManager.GetString("GeneralMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box if you experience graphical glitches.
        /// </summary>
        internal static string GraphicalGlitches {
            get {
                return ResourceManager.GetString("GraphicalGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Settings.
        /// </summary>
        internal static string MusicHeader {
            get {
                return ResourceManager.GetString("MusicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Background Music.
        /// </summary>
        internal static string NoBkgMusic {
            get {
                return ResourceManager.GetString("NoBkgMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sound Effects.
        /// </summary>
        internal static string NoSoundFx {
            get {
                return ResourceManager.GetString("NoSoundFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options....
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
    }
}
